/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IReceiveULNInterface extends Interface {
  getFunction(
    nameOrSignature: "getVerificationStatus" | "isVerified" | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getVerificationStatus",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerificationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface IReceiveULN extends BaseContract {
  connect(runner?: ContractRunner | null): IReceiveULN;
  waitForDeployment(): Promise<this>;

  interface: IReceiveULNInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVerificationStatus: TypedContractMethod<
    [
      _srcEid: BigNumberish,
      _dstEid: BigNumberish,
      _headerHash: BytesLike,
      _payloadHash: BytesLike
    ],
    [[bigint, bigint] & { verifiedBy: bigint; requiredDVNs: bigint }],
    "view"
  >;

  isVerified: TypedContractMethod<
    [_headerHash: BytesLike, _payloadHash: BytesLike],
    [boolean],
    "view"
  >;

  verify: TypedContractMethod<
    [
      _packetHeader: BytesLike,
      _payloadHash: BytesLike,
      _confirmations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVerificationStatus"
  ): TypedContractMethod<
    [
      _srcEid: BigNumberish,
      _dstEid: BigNumberish,
      _headerHash: BytesLike,
      _payloadHash: BytesLike
    ],
    [[bigint, bigint] & { verifiedBy: bigint; requiredDVNs: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<
    [_headerHash: BytesLike, _payloadHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      _packetHeader: BytesLike,
      _payloadHash: BytesLike,
      _confirmations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
