/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IKeyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getOperatorKey" | "registerKey"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getOperatorKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerKey",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOperatorKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerKey",
    data: BytesLike
  ): Result;
}

export interface IKeyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IKeyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IKeyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOperatorKey: TypedContractMethod<
    [operator: AddressLike],
    [[string, boolean] & { blsKey: string; isActive: boolean }],
    "view"
  >;

  registerKey: TypedContractMethod<
    [blsPublicKey: BytesLike, proofOfPossession: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOperatorKey"
  ): TypedContractMethod<
    [operator: AddressLike],
    [[string, boolean] & { blsKey: string; isActive: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerKey"
  ): TypedContractMethod<
    [blsPublicKey: BytesLike, proofOfPossession: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
