/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKeyRegistry } from "./IKeyRegistry";
export type { INetwork } from "./INetwork";
export type { ISettlement } from "./ISettlement";
export type { IValSetDriver } from "./IValSetDriver";
export type { IVotingPowerProvider } from "./IVotingPowerProvider";
