/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface INetworkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMinValidatorStake"
      | "getNetworkId"
      | "getQuorumThreshold"
      | "isOperatorRegistered"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMinValidatorStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuorumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOperatorRegistered",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMinValidatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuorumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperatorRegistered",
    data: BytesLike
  ): Result;
}

export interface INetwork extends BaseContract {
  connect(runner?: ContractRunner | null): INetwork;
  waitForDeployment(): Promise<this>;

  interface: INetworkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMinValidatorStake: TypedContractMethod<[], [bigint], "view">;

  getNetworkId: TypedContractMethod<[], [bigint], "view">;

  getQuorumThreshold: TypedContractMethod<[], [bigint], "view">;

  isOperatorRegistered: TypedContractMethod<
    [operator: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMinValidatorStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNetworkId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuorumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isOperatorRegistered"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;

  filters: {};
}
