/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitValSetHeader"
      | "getLatestValSetHeader"
      | "verifySignature"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "commitValSetHeader",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestValSetHeader",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitValSetHeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestValSetHeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;
}

export interface ISettlement extends BaseContract {
  connect(runner?: ContractRunner | null): ISettlement;
  waitForDeployment(): Promise<this>;

  interface: ISettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitValSetHeader: TypedContractMethod<
    [epoch: BigNumberish, headerHash: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getLatestValSetHeader: TypedContractMethod<[], [[string, bigint]], "view">;

  verifySignature: TypedContractMethod<
    [
      messageHash: BytesLike,
      aggregatedSignature: BytesLike,
      nonSignerPubkeys: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitValSetHeader"
  ): TypedContractMethod<
    [epoch: BigNumberish, headerHash: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLatestValSetHeader"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "verifySignature"
  ): TypedContractMethod<
    [
      messageHash: BytesLike,
      aggregatedSignature: BytesLike,
      nonSignerPubkeys: BytesLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
