/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IVotingPowerProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getOperatorVotingPowerAt"
      | "getOperatorVotingPowers"
      | "getTotalVotingPowerAt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getOperatorVotingPowerAt",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorVotingPowers",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVotingPowerAt",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOperatorVotingPowerAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorVotingPowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVotingPowerAt",
    data: BytesLike
  ): Result;
}

export interface IVotingPowerProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IVotingPowerProvider;
  waitForDeployment(): Promise<this>;

  interface: IVotingPowerProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOperatorVotingPowerAt: TypedContractMethod<
    [operator: AddressLike, timestamp: BigNumberish, hint: BytesLike],
    [bigint],
    "view"
  >;

  getOperatorVotingPowers: TypedContractMethod<
    [operators: AddressLike[]],
    [bigint[]],
    "view"
  >;

  getTotalVotingPowerAt: TypedContractMethod<
    [timestamp: BigNumberish, hint: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOperatorVotingPowerAt"
  ): TypedContractMethod<
    [operator: AddressLike, timestamp: BigNumberish, hint: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOperatorVotingPowers"
  ): TypedContractMethod<[operators: AddressLike[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalVotingPowerAt"
  ): TypedContractMethod<
    [timestamp: BigNumberish, hint: BytesLike],
    [bigint],
    "view"
  >;

  filters: {};
}
