/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILayerZeroDVN,
  ILayerZeroDVNInterface,
} from "../../../contracts/interfaces/ILayerZeroDVN";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "srcEid",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "dstEid",
            type: "uint32",
          },
          {
            internalType: "bytes",
            name: "header",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "payloadHash",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "confirmations",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
        ],
        internalType: "struct ILayerZeroDVN.AssignJobParam",
        name: "_param",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "_options",
        type: "bytes",
      },
    ],
    name: "assignJob",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_dstEid",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "_confirmations",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_options",
        type: "bytes",
      },
    ],
    name: "getFee",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILayerZeroDVN__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroDVNInterface {
    return new Interface(_abi) as ILayerZeroDVNInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILayerZeroDVN {
    return new Contract(address, _abi, runner) as unknown as ILayerZeroDVN;
  }
}
