/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReceiveULN,
  IReceiveULNInterface,
} from "../../../contracts/interfaces/IReceiveULN";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_srcEid",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_dstEid",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "_headerHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_payloadHash",
        type: "bytes32",
      },
    ],
    name: "getVerificationStatus",
    outputs: [
      {
        internalType: "uint256",
        name: "verifiedBy",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "requiredDVNs",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_headerHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_payloadHash",
        type: "bytes32",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_packetHeader",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "_payloadHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "_confirmations",
        type: "uint64",
      },
    ],
    name: "verify",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReceiveULN__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiveULNInterface {
    return new Interface(_abi) as IReceiveULNInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReceiveULN {
    return new Contract(address, _abi, runner) as unknown as IReceiveULN;
  }
}
