/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INetwork,
  INetworkInterface,
} from "../../../../contracts/interfaces/ISymbioticIntegration.sol/INetwork";

const _abi = [
  {
    inputs: [],
    name: "getMinValidatorStake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNetworkId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getQuorumThreshold",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isOperatorRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INetwork__factory {
  static readonly abi = _abi;
  static createInterface(): INetworkInterface {
    return new Interface(_abi) as INetworkInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INetwork {
    return new Contract(address, _abi, runner) as unknown as INetwork;
  }
}
